# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- uses: ./docs@main
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Make Sphinx Docs!


      - uses: IPVS-AS/pusion@main
        with:
          docs-folder: "docs/"
          build-command: "sphinx-build -b html . _build"

      - uses: IPVS-AS/pusion@main
        with:
          docs-folder: "docs/"
          pre-build-command: "sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make latexpdf"

      # Runs a set of commands using the runners shell
      - name: Run commands
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install .
          pip3 install sphinx sphinx_rtd_theme sphinxcontrib-bibtex

      - name: Run bat script on Bash
        shell: bash
        run: sudo ./docs/make.bat html
      ./home/runner/work/pusion/pusion/docs/make html
      ./make html
      ./make latex PAPER=a4
          
